version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seeker_app
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: seeker
      DB_USERNAME: root
      DB_PASSWORD: secret
    entrypoint: ["sh", "/var/www/docker-entrypoint.sh"]

  db:
    image: mysql:8
    container_name: seeker_db
    restart: always
    environment:
      MYSQL_DATABASE: seeker
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
